server:
  port: 8762

spring:
  application:
    name: server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#HystrixDashboard
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"