server:
  port: 8772

spring:
  application:
    name: authorization-server


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dx_cloud?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root

  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456


mybatis:
  configuration:
    map-underscore-to-camel-case: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#log
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    com.springboot.auth: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

