server:
  port: 8769

spring:
  application:
    name: config-server
  profiles:
    active: native  # 配置使用本地储存
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
        git:
          uri: https://github.com/rockstarsteve/dx-config-data
          #uri: https://github.com/forezp/SpringcloudConfig/
          #search-paths: /respo
          default-label: master
          username:
          password:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/