server:
  port: 8769

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "docs.spring.io"
            allowedMethods:
            - GET
      routes:
      # to 136  http://www.163.com/
      - id: 163_route
        uri: http://www.163.com/
        predicates:
        - Path=/163
      # to auth
      - id: auth_route
        uri: lb://server
        predicates:
        - Path=/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

