server:
  port: 8763

spring:
  application:
    name: service-feign


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
