server:
  port: 8773

spring:
  application:
    name: config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
    config:
      name: application  #文件前缀名称
      discovery:
        serviceId: config-server
        enabled: true
      profile: dev
      label: master

  rabbitmq:
    username: steve
    password: steve
    port: 5672
    host: localhost

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

dx: ssssssssssssssssssssssss



