#server:
#  port: 8772

spring:
  application:
    name: config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
    config:
      name: application  #对应的配置服务中的应用名称
      discovery:
        enabled: true  #启用发现服务功能
        serviceId: config-server  #指定服务名称
      profile: dev
      label: master

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
