#server:
#  port: 8772

spring:
  application:
    name: config-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
    config:
      name: application  #文件前缀名称
      discovery:
        serviceId: config-server
        enabled: true
      profile: dev
      label: master




  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
